# Generated by Django 6.0.4 on 2026-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylisting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='status',
            field=models.CharField(choices=[('Under approval', 'Under approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Under approval', max_length=20),
        ),
    ]
