# Generated by Django 6.0.3 on 2026-04-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylisting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='owner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
