# Generated by Django 6.0.3 on 2026-04-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylisting', '0002_properties_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='price_per_month',
        ),
        migrations.AddField(
            model_name='properties',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
