# Generated by Django 6.0.4 on 2026-05-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylisting', '0002_properties_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(choices=[('Under approval', 'Under approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending delete', 'Pending delete')], default='Under approval', max_length=20),
        ),
    ]
