# Generated by Django 6.0.4 on 2026-04-25 06:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertylisting', '0003_remove_properties_price_per_month_properties_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
