# Generated by Django 6.0.4 on 2026-04-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylisting', '0004_alter_properties_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='area',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='properties',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='properties',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
