# Generated by Django 6.0.4 on 2026-05-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertylisting', '0007_properties_property_ref'),
        ('propertylisting', '0009_remove_properties_id_properties_property_ref'),
    ]

    operations = [
    ]
