# Generated by Django 6.0.4 on 2026-05-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertylisting', '0007_properties_property_ref'),
    ]

    operations = [
        # Step 1: Add property_ref field
        migrations.AddField(
            model_name='properties',
            name='property_ref',
            field=models.CharField(default='TEMP', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
